# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14da90bdbbab48220d752efdd4ce39bead81d1fdbb6dabbfdfe84fb2f7f6530a3144a23748a4ed1f5c4e3af4ff1ac234cb280613f1a611343f582960025db60b

test:
  secret_key_base: d3c8f3d34544b1d36340c4298ed5075f698794c3efc90ac5e18c8ab7d499f418de874f2ef412bb351ffb65c3fea95e7441d9068979f1550b52e8f913fdf58b28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
